# -*- coding: utf-8 -*-
"""Smart banking management system

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z3YD4mHyodx91CMdhIgQYL5hmZ_wMmXT
"""

import json
import os
from datetime import datetime

FILE_NAME = "bank_data .json"

def load_data():
    if not os.path.exists(FILE_NAME):
        return {}
    with open(FILE_NAME, "r") as file:
        return json.load(file)
def save_data(data):
    with open(FILE_NAME, "w") as file:
        json.dump(data, file, indent=4)
def generate_account_number():
    return str(datetime.now().timestamp()).replace(".", "")

class BankAccount:
    def __init__(self, name, balance=0):
        self.name = name
        self.account_number = generate_account_number()
        self.balance = balance
        self.transactions = []

    def deposit(self, amount):
        self.balance += amount
        self.transactions.append(f"Deposited {amount}")

    def withdraw(self, amount):
        if amount > self.balance:
            raise ValueError("Insufficient balance!")
        self.balance -= amount
        self.transactions.append(f"Withdrew {amount}")

    def to_dict(self):
        return {
            "name": self.name,
            "account_number": self.account_number,
            "balance": self.balance,
            "transactions": self.transactions
        }

def create_account(data):
    name = input("Enter account holder name: ")
    initial_balance = float(input("Enter initial deposit: "))

    account = BankAccount(name, initial_balance)
    data[account.account_number] = account.to_dict()

    save_data(data)
    print("Account created successfully!")
    print("Account Number:", account.account_number)


def view_account(data):
    acc_num = input("Enter account number: ")
    account = data.get(acc_num)

    if account:
        print("\n--- Account Details ---")
        print("Name:", account["name"])
        print("Balance:", account["balance"])
        print("Transactions:")
        for t in account["transactions"]:
            print("-", t)
    else:
        print("Account not found!")


def deposit_money(data):
    acc_num = input("Enter account number: ")
    amount = float(input("Enter amount to deposit: "))

    if acc_num in data:
        data[acc_num]["balance"] += amount
        data[acc_num]["transactions"].append(f"Deposited {amount}")
        save_data(data)
        print("Deposit successful!")
    else:
        print("Account not found!")


def withdraw_money(data):
    acc_num = input("Enter account number: ")
    amount = float(input("Enter amount to withdraw: "))

    if acc_num in data:
        if data[acc_num]["balance"] >= amount:
            data[acc_num]["balance"] -= amount
            data[acc_num]["transactions"].append(f"Withdrew {amount}")
            save_data(data)
            print("Withdrawal successful!")
        else:
            print("Insufficient balance!")
    else:
        print("Account not found!")


def delete_account(data):
    acc_num = input("Enter account number to delete: ")

    if acc_num in data:
        del data[acc_num]
        save_data(data)
        print("Account deleted successfully!")
    else:
        print("Account not found!")

def main():
    data = load_data()

    while True:
        print("\n====== Smart Bank System ======")
        print("1. Create Account")
        print("2. View Account")
        print("3. Deposit Money")
        print("4. Withdraw Money")
        print("5. Delete Account")
        print("6. Exit")

        choice = input("Select option: ")

        try:
            if choice == "1":
                create_account(data)
            elif choice == "2":
                view_account(data)
            elif choice == "3":
                deposit_money(data)
            elif choice == "4":
                withdraw_money(data)
            elif choice == "5":
                delete_account(data)
            elif choice == "6":
                print("Thank you for using Smart Bank System!")
                break
            else:
                print("Invalid choice!")
        except ValueError as ve:
            print("Error:", ve)
        except Exception as e:
            print("Unexpected error:", e)


if __name__ == "__main__":
    main()

